name: coronavirus-screenshots

on: push

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Cypress runner
        uses: cypress-io/github-action@v2
        timeout-minutes: 10

      - uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: ./output/screenshots/spec.js
