name: coronavirus-screenshots

on:
  push:
  schedule:
    - cron:  '0 4 * * *' # daily at 4am

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Cypress runner
        uses: cypress-io/github-action@v2
        timeout-minutes: 10

      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: screenshots
      #     path: ./output/screenshots/spec.js
      #     if-no-files-found: error
      #     retention-days: 14

      - name: Post to Imgur
        run: |
          for i in ./output/screenshots/spec.js/*.png; do curl -s -o /dev/null -XPOST "https://api.imgur.com/3/image" -H "Authorization: Client-ID ${{ secrets.IMGUR_CLIENT }}" -F "album=${{ secrets.IMGUR_ALBUM }}" -F "type=file" -F "title=${i}" -F "description=${i}" -F "image=@${i}"; done
